### ISSUE TITLE
debug ava tests in vscode not working

### ISSUE THREAD

**Issue by rbenzazon** [avajs/ava-docs#62]
Hello,
I followed the [documentation ](https://github.com/avajs/ava/blob/master/docs/recipes/debugging-with-vscode.md )to configure vscode for debugging and I when I start a test I get the following error in the debug console :  
× debug does not exist.

trying in cmd this line :  
C:\projectfolder/node_modules/.bin/ava.CMD debug
gives the same output :  
× debug does not exist.

I don't know if it's a deprecated documentation problem or a bug/issue

**Comment by novemberborn** [comment]
The documentation is for AVA 3 which was released yesterday.

**Comment by rbenzazon** [comment]
Hello,

Thanks, I just realized too by myself. I don't know if I should upgrade or use the old documentation. Do you know if AVA 3 introduce breaking changes?

best regards

**Comment by novemberborn** [comment]
I suggest you consult the release notes: https://github.com/avajs/ava/releases/tag/v3.0.0
